"""Stage 5: synthetic defect generation for U-Net training.

A defect is parametrized by its *strength* = -a / I_local (absorption fraction
of the local background above the dark pedestal). Strengths are sampled from
the empirical distribution of real detected events, so amplitude automatically
scales with the local background as the cross-term physics dictates; a
configurable fraction is pushed below the detection SNR to create hard
positives. Rendering uses exact band-limited (Fourier) sub-pixel placement of
the estimated impulse response, a shot-noise-consistent noise increment, 12-bit
clipping, and diff regenerated by the same subtraction pipeline so the
(defect, reference, diff) triplet stays consistent.

Known approximation: for dark defects the local shot noise should *decrease*
slightly where signal is removed; noise cannot be subtracted from a real image,
so synthetic dark defects carry up to ~15% excess local noise at the deepest
pixel. This is second-order and confined to a few pixels.
"""
from __future__ import annotations

import csv
import json
import os

import numpy as np

from .diffimg import compute_diff
from .epsf import EPSFModel


def fit_strength_distribution(events: list, pedestal: float) -> dict:
    """Log-normal fit of strength = -a / max(I_local - pedestal, eps)."""
    a = np.array([ev.a for ev in events if ev.kept and ev.a < 0])
    il = np.array([ev.i_local for ev in events if ev.kept and ev.a < 0])
    strength = -a / np.maximum(il - pedestal, 1.0)
    strength = strength[(strength > 0) & np.isfinite(strength)]
    ls = np.log(strength)
    return {
        "mu_log": float(np.median(ls)),
        "sigma_log": float(1.4826 * np.median(np.abs(ls - np.median(ls)))),
        "n": int(len(strength)),
        "strength_min": float(strength.min()),
        "strength_max": float(strength.max()),
    }


def sample_strength(rng, dist: dict, cfg) -> float:
    s = float(np.exp(rng.normal(dist["mu_log"], dist["sigma_log"])))
    s = min(s, 2.0 * dist["strength_max"])
    if rng.random() < cfg.synth_weak_frac:
        lo, hi = cfg.synth_weak_scale
        s *= float(rng.uniform(lo, hi))
    return s


def render_kernel(model: EPSFModel, fy: float, fx: float) -> np.ndarray:
    """Pixel-grid kernel of h centered at fractional offset (fy, fx)."""
    return model.render(fy, fx)


def _far_from_hot(y: int, x: int, hot_yx: np.ndarray, min_dist: float) -> bool:
    if hot_yx.size == 0:
        return True
    d2 = (hot_yx[:, 0] - y) ** 2 + (hot_yx[:, 1] - x) ** 2
    return bool(d2.min() > min_dist ** 2)


def synthesize(pairs_by_id: dict, clean_ids: list, hot_by_id: dict,
               h: np.ndarray, noise_model, strength_dist: dict, cfg,
               out_dir: str, n_samples: int, negative_frac: float = 0.3,
               seed: int = 0, load_pair_fn=None) -> list:
    """Write SYN_{i}_def/_ref1/_diff/_mask .npy files plus a catalog."""
    os.makedirs(out_dir, exist_ok=True)
    rng = np.random.default_rng(seed)
    model = EPSFModel(h, cfg.oversample, cfg.window_radius())
    R = cfg.window_radius()
    margin = max(cfg.synth_margin_px, R + 2)
    rows = []

    for i in range(n_samples):
        pid = clean_ids[int(rng.integers(len(clean_ids)))]
        d_img, r_img = load_pair_fn(pairs_by_id[pid])
        hot = hot_by_id.get(pid, np.empty((0, 2)))
        make_defect = rng.random() >= negative_frac

        row = {"index": i, "source_pair": pid, "has_defect": int(make_defect),
               "y": -1.0, "x": -1.0, "a": 0.0, "strength": 0.0, "i_local": 0.0}
        d_new = d_img.copy()
        mask = np.zeros(d_img.shape, dtype=np.uint8)

        if make_defect:
            for _ in range(200):
                y = int(rng.integers(margin, d_img.shape[0] - margin))
                x = int(rng.integers(margin, d_img.shape[1] - margin))
                if _far_from_hot(y, x, hot, cfg.synth_hot_dist_px):
                    break
            fy = float(rng.uniform(-0.5, 0.5))
            fx = float(rng.uniform(-0.5, 0.5))
            i_local = float(np.mean(r_img[y - 2: y + 3, x - 2: x + 3]))
            strength = sample_strength(rng, strength_dist, cfg)
            a = -strength * max(i_local - noise_model.pedestal, 0.0)
            kern = render_kernel(model, fy, fx)
            sl = (slice(y - R, y + R + 1), slice(x - R, x + R + 1))
            signal = a * kern
            d_new[sl] += signal
            # shot-noise increment (only where signal increases intensity)
            sig0 = noise_model.sigma_image_at(d_img[sl])
            sig1 = noise_model.sigma_image_at(np.maximum(d_img[sl] + signal, 0))
            extra = np.sqrt(np.maximum(sig1 ** 2 - sig0 ** 2, 0.0))
            d_new[sl] += rng.normal(0.0, 1.0, signal.shape) * extra
            # ground-truth mask
            sig_site = float(noise_model.sigma_diff_at(i_local))
            m = np.abs(signal) > cfg.synth_mask_k * sig_site
            yy, xx = np.mgrid[-R: R + 1, -R: R + 1]
            m |= np.hypot(yy - fy, xx - fx) <= cfg.synth_mask_min_r
            mask[sl] |= m.astype(np.uint8)
            row.update({"y": y + fy, "x": x + fx, "a": float(a),
                        "strength": float(strength), "i_local": i_local})

        d_new = np.clip(np.rint(d_new), 0, 4095).astype(np.uint16)
        r_out = np.clip(np.rint(r_img), 0, 4095).astype(np.uint16)
        dres = compute_diff(d_new.astype(np.float64),
                            r_out.astype(np.float64), cfg)
        base = os.path.join(out_dir, f"SYN_{i:05d}")
        np.save(base + "_def.npy", d_new)
        np.save(base + "_ref1.npy", r_out)
        np.save(base + "_diff.npy", dres.diff.astype(np.float32))
        np.save(base + "_mask.npy", mask)
        rows.append(row)

    with open(os.path.join(out_dir, "catalog.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    with open(os.path.join(out_dir, "synth_params.json"), "w") as f:
        json.dump({"n_samples": n_samples, "negative_frac": negative_frac,
                   "strength_dist": strength_dist, "seed": seed}, f, indent=2)
    return rows
